# Generated by Django 5.0.5 on 2024-05-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up',
            name='Phone_Number',
            field=models.IntegerField(default='', max_length=10),
        ),
    ]
