# Generated by Django 5.0.5 on 2024-05-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_sign_up_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up',
            name='Phone_Number',
            field=models.IntegerField(default=''),
        ),
    ]
