# Generated by Django 4.0.10 on 2024-05-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_sign_up_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign_up',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
